// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UTS_Project_Efengsi_Rahmanto_Zalukhu.Models;

#nullable disable

namespace UTS_Project_Efengsi_Rahmanto_Zalukhu.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250716171906_d")]
    partial class d
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UTS_Project_Efengsi_Rahmanto_Zalukhu.Models.DB.Pesanan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlamatPembeli")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdProduk")
                        .HasColumnType("int");

                    b.Property<int>("JumlaH")
                        .HasColumnType("int");

                    b.Property<string>("NamePembeli")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("TanggalPesanan")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Pesanans");
                });

            modelBuilder.Entity("UTS_Project_Efengsi_Rahmanto_Zalukhu.Models.DB.Produk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameProduk")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TanggalKadalwarsa")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Produks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2025, 7, 17, 0, 19, 6, 151, DateTimeKind.Local).AddTicks(2558),
                            Harga = 100000m,
                            ImagePath = "Images/Produk/aa.jpg",
                            NameProduk = "Produk Sample 1",
                            Supplier = "Supplier A",
                            TanggalKadalwarsa = new DateTime(2026, 7, 17, 0, 19, 6, 151, DateTimeKind.Local).AddTicks(2540)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2025, 7, 17, 0, 19, 6, 151, DateTimeKind.Local).AddTicks(2564),
                            Harga = 150000m,
                            ImagePath = "Images/Produk/aa.jpg",
                            NameProduk = "Produk Sample 2",
                            Supplier = "Supplier B",
                            TanggalKadalwarsa = new DateTime(2027, 7, 17, 0, 19, 6, 151, DateTimeKind.Local).AddTicks(2562)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
