// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UTS_Project_Efengsi_Rahmanto_Zalukhu.Models;

#nullable disable

namespace UTS_Project_Efengsi_Rahmanto_Zalukhu.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UTS_Project_Efengsi_Rahmanto_Zalukhu.Models.DB.Pesanan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlamatPembeli")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdProduk")
                        .HasColumnType("int");

                    b.Property<int>("JumlaH")
                        .HasColumnType("int");

                    b.Property<string>("NamePembeli")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("TanggalPesanan")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Pesanans");
                });

            modelBuilder.Entity("UTS_Project_Efengsi_Rahmanto_Zalukhu.Models.DB.Produk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("NameProduk")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TanggalKadalwarsa")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Produks");
                });
#pragma warning restore 612, 618
        }
    }
}
